### ISSUE TITLE
Add ability to view gcf and mf details from the network

### ISSUE THREAD

**Issue by sdrogers** [sdrogers/mfgcf#1]
Selecting a node in the network should make the MF/GCF information visible, e.g. here:
http://sdrogers.pythonanywhere.com/linker/showgcf/15420
visible on the network page, or in a new tab
ditto for MF
the urls are the GCF and MF IDs

**Comment by joewandy** [comment]
I merged the Show Graph and Show Links pages into a single page, then I made the data table of nodes to filter itself based on the nodes selected in the network. What do you think?

**Comment by justinjjvanderhooft** [comment]
Your uploaded screenshot looks good! Does the table information links back to a page with more information on the GCFs and MFs?
I mainly used the Show Links page so far to search for particular GCFs or MFs and find their links. I guess that will be possible at some point using a search function? Or how do we envision that?

**Comment by joewandy** [comment]
From slack:

1. ~~Select a node by clicking on it. This node gets highlighted, the non-selected portion of the network is greyed out, and the mfgcf table below is filtered to show information on the currently selected node~~. Same when an edge is selected.
2. ~~Display library IDs associated with the MF and MiBIG BGCs associated with the GCF in the table (both objects have @attribute methods to extract that info)~~.
3. ~~Make the network respond to the table and vice versa (currently it's only one-way)~~, e.g. I typed in 0.000 into the search and it pulled up all the rows with p-values starting 0.000. We can make these links (and the respective nodes) showed up in the network
4. ~~Make the div/svg for the network bigger please~~?
5. ~~For the table, include links that have the p-values below the threshold *and* validated ones (even if higher p-value). This is how it works for the graph~~.

**Comment by joewandy** [comment]
Now if we type a node name in the search box, it will also highlight this in the table.
