### ISSUE TITLE
Passing threshold to graph

### ISSUE THREAD

**Issue by sdrogers** [sdrogers/mfgcf#8]
Django form defaults to scientific notation when the threshold is particularly small e.g. 1e-5. The regular expression in the urls.py doesn't match this so we get page not found

**Comment by joewandy** [comment]
How about the commit above? Although it feels that a proper solution would be not to encode the threshold in the url.

**Comment by sdrogers** [comment]
that should work, and yep, there would be a better solution but lets stick with this for the time being...other stuff is more important just now...
